swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /bank/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Bank (Client)
        - Bank (Banker)
        - Bank (Admin)
      summary: Get accounts
      description: get all accounts available
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '401':
          description : Unauthorized
        '500':
          description: Internal Server Error
  /bank/accounts/{account_id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Bank (Client)
        - Bank (Banker)
        - Bank (Admin)
      summary: Get account transactions by Account Id
      description: Get account transactions by Account Id
      parameters:
        - in: path
          name: account_id
          description: account id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully get the account
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '401':
          description : Unauthorized  
        '500':
          description: Internal Server Error
  /bank/accounts/{account_id}/transactions/{transaction_id}:
    put:
      security:
        - Bearer: []
      tags:
        - Bank (Client)
      summary: Update transaction by Id
      description: Update a transaction note or/and category using its Id.
      parameters:
        - in: path
          name: account_id
          description: account id
          required: true
          type: string
        - in: path
          name: transaction_id
          description: Update transaction note and category 
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction note and category 
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Not found
        '401':
          description : Unauthorized  
        '500':
          description: Internal Server Error
          
          
          
  /panel/users:
    get:
      security:
        - Bearer: []
      tags:
        - Bank (Banker)
        - Bank (Admin)
      summary: Get all Clients from the Bank
      description: Get all Clients from the bank to add transactions or accounts
      produces:
        - application/json
      responses:
        '200':
          description: Clients fetched successfully
        '401': 
          description: Unauthorized
        '404':
          description: Clients not found
        '500':
          description: Internal Server Error
          
  /panel/users/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Bank (Banker)
        - Bank (Admin)
      summary: Get a Client by his Id
      description: Get a client by his Id to update or delete him.
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: Client Id
          required: true
          type: string
      responses:
        '200':
          description: Client retrieved successfully
        '400':
          description: Client Id required!
        '404':
          description: No user found!
        '500':
          description: Error Server
                  
          
  /panel/banker/addAccount:
    post: 
      security:
        - Bearer: []
      tags: 
        - Bank (Banker)
      summary: Add an account
      description: Add an account linked to an existing Client.
      produces: 
        - application/json
      parameters:
        - in: body
          name: body
          description: Add an account with a userId (Client ID) and the initial balance.
          required: true
          schema:
            $ref: '#/definitions/addAccount'
      responses:
        '201':
          description: Account created successfully!
        '400':
          description: All fields are required
        '500':
          description: Error creating account
  
  
  /panel/banker/addTransaction:
    post:
      security:
        - Bearer: []
      tags: 
        - Bank (Banker)
      summary: Add transaction to an existing account
      description: Add a transaction to an account linked to a client
      produces: 
        - application/json  
      parameters:
        - in: body
          name: body
          description: Add a transaction with accId, desc, amount, balance.
          required: true
          schema:
            $ref: '#/definitions/addTransaction'
      responses:
        '201': 
          description: Transaction created sucessfully
        '400':
          description: All fields are required
        '404':
          description: No account found with this ID
        '500': 
          description: Error creating the transaction
        
  /panel/admin/deleteAccount/{accountID}:
    delete:
      security:
        - Bearer: []
      tags:
        - Bank (Admin)
      summary: Delete an account
      description: Delete an account
      produces:
        - application/json
      parameters:
        - in: path
          name: accountID
          type: string
          required: true
      responses:
        '200':
          description: Account deleted successfully
        '400': 
          description: All fields are required
        '500':
          description: Error deleting the account
 
          
  /panel/admin/deleteTransaction/{transactionID}:
    delete:
      security:
        - Bearer: []
      tags:
        - Bank (Admin)
      summary: Delete a transaction
      description: Delete a transaction
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionID
          type: string
          required: true
      responses:
        '200':
          description: Transaction deleted successfully
        '400': 
          description: All fields are required
        '500':
          description: Error deleting the transaction
          
          
  /panel/admin/upUser/{userID}:
    put:
      security:
        - Bearer: []
      tags:
        - Bank (Admin)
      summary: Update Client infos
      description: Update any information of a Client
      produces: 
        - application/json
      parameters:
        - in: path
          name: userID
          type: string
          required: true
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/updateClient'
      responses:
        '200':
          description: Client updated sucessfully
        '400':
          description: All fields are required
        '500':
          description: Error updating the Client
          
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  addAccount:
    properties:
      user:
        type: string
        description: Client ID
      availableBalance:
        type: number
        description: Available balance on the account
  Accounts:
    properties:
      accountId:
        type: string
        description: account id
      availableBalance:
        type: string
        description: available balance on the account
  addTransaction:
    properties:
      accId:
        type: string
        description: Account Id to linked the transaction to it
      desc: 
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance: 
        type: number
        description: balance left after transaction
      note:
        type: string
      category:
        type: string
  Transactions:
    properties:
      transactions:
        properties:
          date:
            type: string
            description: Transaction date
          description:
            type: string
            description: Transaction description
          amount:
            type: number
            description: Transaction amount
          balance:
            type: string
            description: balance  
          transactionType:
            type: string
            description: What kind of transaction
          note: 
            type: string
            description: note to describe the transaction
          category:
            type: string
            description: transaction's category
  Transaction:
    properties:
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: string
        description: balance    
      transactionType:
        type: string
        description: What kind of transaction
      note: 
        type: string
        description: note to describe the transaction
      category:
        type: string
        description: transaction's category 
  updateClient:
    properties:
      email:
        type: string
      lastname:
        type: string
      roles:
        type: object
  UpdateTransaction:
    properties:
      note: 
        type: string
      category: 
        type: string