swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /bank/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Bank
      summary: Get accounts
      description: get all accounts available
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '401':
          description : Unauthorized
        '500':
          description: Internal Server Error
  /bank/accounts/{account_id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Bank
      summary: Get account transactions by Account Id
      description: Get account transactions by Account Id
      parameters:
        - in: path
          name: account_id
          description: account id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully get the account
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '401':
          description : Unauthorized  
        '500':
          description: Internal Server Error
  /bank/accounts/{account_id}/transactions/{transaction_id}:
    put:
      security:
        - Bearer: []
      tags:
        - Bank
      summary: Update transaction by Id
      description: Update a transaction note or/and category using its Id.
      parameters:
        - in: path
          name: account_id
          description: account id
          required: true
          type: string
        - in: path
          name: transaction_id
          description: Update transaction note and category 
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction note and category 
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Not found
        '401':
          description : Unauthorized  
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Accounts:
    properties:
      accountId:
        type: string
        description: account id
      availableBalance:
        type: string
        description: available balance on the account
  Transactions:
    properties:
      transactions:
        properties:
          date:
            type: string
            description: Transaction date
          description:
            type: string
            description: Transaction description
          amount:
            type: number
            description: Transaction amount
          balance:
            type: string
            description: balance  
          transactionType:
            type: string
            description: What kind of transaction
          note: 
            type: string
            description: note to describe the transaction
          category:
            type: string
            description: transaction's category
  Transaction:
    properties:
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: string
        description: balance    
      transactionType:
        type: string
        description: What kind of transaction
      note: 
        type: string
        description: note to describe the transaction
      category:
        type: string
        description: transaction's category  
  UpdateTransaction:
    properties:
      note: 
        type: string
      category: 
        type: string